/*
 * Copyright 2010-2014 Laszlo Balazs-Csiki
 *
 * This file is part of Pixelitor. Pixelitor is free software: you
 * can redistribute it and/or modify it under the terms of the GNU
 * General Public License, version 3 as published by the Free
 * Software Foundation.
 *
 * Pixelitor is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Pixelitor.  If not, see <http://www.gnu.org/licenses/>.
 */
/*
@TODO MERGE
package dictionary;

import templates.*;
import MSLCC.MSLCC;
import MSLCC.IntroVideo;
import com.idrt.flashCards;
import com.idrt.SignOnlyDictionary;
*/
package pixelitor;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextField;


import org.jdesktop.swingx.JXCategory;
import org.jdesktop.swingx.tips.CategoryLoader;
import org.jdesktop.swingx.tips.CategoryModel;
import pixelitor.utils.AppPreferences;
import pixelitor.utils.Dialogs;

import javax.swing.*;
import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;
import java.util.prefs.Preferences;


import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author teddyted
 */
public class categoriesMain extends javax.swing.JFrame {

    /**
     * Creates new form templatesMain
     */
    public categoriesMain() {
        initComponents();
    }
    
//@TODO    private com.idrt.flashCards frameFlashCards;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ButtonMainMenu = new javax.swing.JButton();
        ButtonQuestion = new javax.swing.JButton();
        ButtonVideo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        allButton = new javax.swing.JButton();
        numbersButton = new javax.swing.JButton();
        
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        ButtonMainMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/b_mainmenu.png"))); // NOI18N
        ButtonMainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonMainMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonMainMenuMouseExited(evt);
            }
        });
        ButtonMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
//@TODO                ButtonMainMenuActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonMainMenu);
        ButtonMainMenu.setBounds(650, 10, 140, 70);

        ButtonQuestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/b_question.png"))); // NOI18N
        ButtonQuestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonQuestionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonQuestionMouseExited(evt);
            }
        });
        jPanel1.add(ButtonQuestion);
        ButtonQuestion.setBounds(10, 10, 70, 50);

        ButtonVideo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/b_video.png"))); // NOI18N
        ButtonVideo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonVideoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonVideoMouseExited(evt);
            }
        });
        ButtonVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
//@TODO                ButtonVideoActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonVideo);
        ButtonVideo.setBounds(10, 550, 70, 50);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IDCRTT/dictionaryMainCategories.png"))); // NOI18N
        jLabel2.setAutoscrolls(true);
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setMaximumSize(new java.awt.Dimension(755, 567));
        jLabel2.setMinimumSize(new java.awt.Dimension(755, 567));
        jLabel2.setPreferredSize(new java.awt.Dimension(755, 567));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, -10, 800, 630);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 255));
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 10, 810, 600);
        
        
        allButton.setBackground(new java.awt.Color(204, 0, 51));
        allButton.setOpaque(false);
        allButton.setContentAreaFilled(false);
        allButton.setBorderPainted(false);
        allButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        allButton.setText("Numbers");
        allButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allButtonActionPerformed(evt);
            }
        });
        
        jPanel1.add(allButton);
        allButton.setBounds(40, 190, 140, 50);
        allButton.setText("All");
        allButton.getAccessibleContext().setAccessibleName("pixelitor");
        
        
        numbersButton.setBackground(new java.awt.Color(204, 0, 51));
        numbersButton.setOpaque(false);
        numbersButton.setContentAreaFilled(false);
        numbersButton.setBorderPainted(false);
        numbersButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        numbersButton.setText("Numbers");
        numbersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbersButtonActionPerformed(evt);
            }
        });
        jPanel1.add(numbersButton);
        numbersButton.setBounds(10, 100, 190, 70);
        numbersButton.getAccessibleContext().setAccessibleName("pixelitor");

    }// </editor-fold> 
    private void allButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        this.setVisible(false);
        numbersMain nMain = new numbersMain("All");
        nMain.setVisible(true);
    }
    /* Elmo a copier pour les autres categories */
    private void numbersButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        this.setVisible(false);
        numbersMain nMain = new numbersMain("Numbers");
        nMain.setVisible(true);
    }
/* @TODO
    private void ButtonMainMenuActionPerformed(java.awt.event.ActionEvent evt) {                                               
        MSLCC MSLCC = new MSLCC();
        MSLCC.setSize(820,660); //pack();
        MSLCC.setVisible(true);
        MSLCC.setLocationRelativeTo(null);
        this.setVisible(false); //radi
    }                                              

    private void ButtonVideoActionPerformed(java.awt.event.ActionEvent evt) {                                            
        IntroVideo IntroVideo = new IntroVideo();
        IntroVideo.setSize(820,660); //pack();
        IntroVideo.setVisible(true);
        IntroVideo.setLocationRelativeTo(null);
        this.setVisible(false); //radi
    }                                           
*/
    private void ButtonMainMenuMouseEntered(java.awt.event.MouseEvent evt) {                                            
        ButtonMainMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/b_mainmenu-hover.png")));
    }                                           

    private void ButtonMainMenuMouseExited(java.awt.event.MouseEvent evt) {                                           
       ButtonMainMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/b_mainmenu.png")));
    }                                          

    private void ButtonQuestionMouseEntered(java.awt.event.MouseEvent evt) {                                            
        ButtonQuestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/b_question-hover.png")));
    }                                           

    private void ButtonQuestionMouseExited(java.awt.event.MouseEvent evt) {                                           
        ButtonQuestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/b_question.png")));
    
    }

    private void ButtonVideoMouseEntered(java.awt.event.MouseEvent evt) {                                         
        ButtonVideo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/b_video-hover.png")));
    
    }                                        

    private void ButtonVideoMouseExited(java.awt.event.MouseEvent evt) {                                        
        ButtonVideo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/b_video.png")));
    
    }                                       

    /**
     * 
     */
    public static void showCategories() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Categories().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton ButtonMainMenu;
    private javax.swing.JButton ButtonQuestion;
    private javax.swing.JButton ButtonVideo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    /* Categories Buttons */
    private javax.swing.JButton allButton;
    private javax.swing.JButton numbersButton;
    // End of variables declaration                   
}
