/*
 * Copyright 2010-2014 Laszlo Balazs-Csiki
 *
 * This file is part of Pixelitor. Pixelitor is free software: you
 * can redistribute it and/or modify it under the terms of the GNU
 * General Public License, version 3 as published by the Free
 * Software Foundation.
 *
 * Pixelitor is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Pixelitor.  If not, see <http://www.gnu.org/licenses/>.
 */
package pixelitor;

import org.jdesktop.swingx.JXCategory;
import org.jdesktop.swingx.tips.CategoryLoader;
import org.jdesktop.swingx.tips.CategoryModel;
import pixelitor.utils.AppPreferences;
import pixelitor.utils.Dialogs;

import javax.swing.*;
import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;
import java.util.prefs.Preferences;


import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;


public class Categories extends javax.swing.JFrame {

    /**
     * Creates new form NumberAddition
     */
    public Categories() {
        initComponents();
    }

        @SuppressWarnings("unchecked")

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        templatesButton = new javax.swing.JButton();
        //allButton = new javax.swing.JButton();

        
        
        allButton = new javax.swing.JButton();
        
        cultureButton = new javax.swing.JButton();
        quantitiesButton = new javax.swing.JButton();
        religionButton = new javax.swing.JButton();
        foodButton = new javax.swing.JButton();
        
        numbersButton = new javax.swing.JButton();
        feelingsButton = new javax.swing.JButton();       
        
        introVideoButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 255));
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setBounds(new java.awt.Rectangle(0, 0, 800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(null);

        
        allButton.setToolTipText("");
        allButton.setBackground(new java.awt.Color(204, 0, 51));
        allButton.setOpaque(false);
        allButton.setContentAreaFilled(false);
        allButton.setBorderPainted(false);
        allButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        allButton.setText("All");
        allButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allButtonActionPerformed(evt);
            }
        });
        allButton.getAccessibleContext().setAccessibleName("pixelitor");
        jPanel1.add(allButton);
        allButton.setBounds(67, 109, 150, 60);
        
        cultureButton.setToolTipText("");
        cultureButton.setBackground(new java.awt.Color(204, 0, 51));
        cultureButton.setOpaque(false);
        cultureButton.setContentAreaFilled(false);
        cultureButton.setBorderPainted(false);
        cultureButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        cultureButton.setText("Culture");
        cultureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cultureButtonActionPerformed(evt);
            }
        });
        cultureButton.getAccessibleContext().setAccessibleName("pixelitor");        
        jPanel1.add(cultureButton);
        cultureButton.setBounds(50, 179, 160, 70);
        
        quantitiesButton.setToolTipText("");
        quantitiesButton.setBackground(new java.awt.Color(204, 0, 51));
        quantitiesButton.setOpaque(false);
        quantitiesButton.setContentAreaFilled(false);
        quantitiesButton.setBorderPainted(false);
        quantitiesButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        quantitiesButton.setText("Quantities");
        quantitiesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantitiesButtonActionPerformed(evt);
            }
        });        
        jPanel1.add(quantitiesButton);
        quantitiesButton.setBounds(7, 259, 170, 80);

        religionButton.setToolTipText("");
        religionButton.setBackground(new java.awt.Color(204, 0, 51));
        religionButton.setOpaque(false);
        religionButton.setContentAreaFilled(false);
        religionButton.setBorderPainted(false);
        religionButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        religionButton.setText("Religion");
        religionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                religionButtonActionPerformed(evt);
            }
        });         
        jPanel1.add(religionButton);
        religionButton.setBounds(10, 360, 140, 80);
        
        foodButton.setToolTipText("");
        foodButton.setBackground(new java.awt.Color(204, 0, 51));
        foodButton.setOpaque(false);
        foodButton.setContentAreaFilled(false);
        foodButton.setBorderPainted(false);
        foodButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        foodButton.setText("Food");
        foodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodButtonActionPerformed(evt);
            }
        }); 
        jPanel1.add(foodButton);
        foodButton.setBounds(0, 500, 120, 50);
        
        
/*
        allButton.setBackground(new java.awt.Color(204, 0, 51));
        allButton.setOpaque(false);
        allButton.setContentAreaFilled(false);
        allButton.setBorderPainted(false);
        allButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        allButton.setText("All");
        allButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allButtonActionPerformed(evt);
            }
        });
        
        jPanel1.add(allButton);
        allButton.setBounds(40, 190, 140, 50);
        allButton.setText("All");
        allButton.getAccessibleContext().setAccessibleName("pixelitor");
        
        
        numbersButton.setBackground(new java.awt.Color(204, 0, 51));
        numbersButton.setOpaque(false);
        numbersButton.setContentAreaFilled(false);
        numbersButton.setBorderPainted(false);
        numbersButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        numbersButton.setText("Numbers");
        numbersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbersButtonActionPerformed(evt);
            }
        });
        jPanel1.add(numbersButton);
        feelingsButton.setBounds(10, 100, 290, 70);
        numbersButton.getAccessibleContext().setAccessibleName("pixelitor");

        feelingsButton.setBackground(new java.awt.Color(204, 0, 51));
        feelingsButton.setOpaque(false);
        feelingsButton.setContentAreaFilled(false);
        feelingsButton.setBorderPainted(false);
        feelingsButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        feelingsButton.setText("Feelings");
        feelingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbersButtonActionPerformed(evt);
            }
        });
        jPanel1.add(feelingsButton);
        feelingsButton.setBounds(10, 100, 190, 70);
        feelingsButton.getAccessibleContext().setAccessibleName("pixelitor");
        
        
        cultureButton.setBackground(new java.awt.Color(204, 0, 51));
        cultureButton.setOpaque(false);
        cultureButton.setContentAreaFilled(false);
        cultureButton.setBorderPainted(false);
        cultureButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        cultureButton.setText("Numbers");
        cultureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cultureButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cultureButton);
        feelingsButton.setBounds(10, 100, 290, 70);
        cultureButton.getAccessibleContext().setAccessibleName("pixelitor");
        
        */
        
        introVideoButton.setText("Video");
        introVideoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introVideoButtonActionPerformed(evt);
            }
        });
        jPanel1.add(introVideoButton);
        introVideoButton.setBounds(650, 520, 79, 29);

        backButton.setText("Back");
        backButton.setToolTipText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton);
        backButton.setBounds(70, 520, 75, 29);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IDCRTT/dictionary_categories_ar.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 755, 567);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>                        
    private static final Logger LOG = Logger.getLogger(Categories.class.getName());

    private void allButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        this.setVisible(false);
        categoryMain nMain = new categoryMain("All");
        nMain.setVisible(true);
    }
    private void numbersButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        this.setVisible(false);
        categoryMain nMain = new categoryMain("Numbers");
        nMain.setVisible(true);
    }
    
    private void cultureButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        this.setVisible(false);
        categoryMain nMain = new categoryMain("Numbers");
        nMain.setVisible(true);
    }

    private void quantitiesButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        this.setVisible(false);
        categoryMain nMain = new categoryMain("Numbers");
        nMain.setVisible(true);
    }
    private void religionButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        this.setVisible(false);
        categoryMain nMain = new categoryMain("Numbers");
        nMain.setVisible(true);
    }
    private void foodButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        this.setVisible(false);
        categoryMain nMain = new categoryMain("Food");
        nMain.setVisible(true);
    }
    
    private void introVideoButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Video frame showing intro.mp4
        //close(); //ne radi
        //NumberAddition.dispose(); //ne radi
        this.setVisible(false); //radi
///        IntroVideo IntroVideo = new IntroVideo();
///        IntroVideo.setVisible(true);
    }

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // Back button
        this.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void showCategories() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Categories().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton backButton;
    private javax.swing.JButton introVideoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton allButton;
    private javax.swing.JButton numbersButton;
    private javax.swing.JButton feelingsButton;
    private javax.swing.JButton templatesButton;
    
    

    private javax.swing.JButton cultureButton;
    private javax.swing.JButton foodButton;
    private javax.swing.JButton quantitiesButton;
    private javax.swing.JButton religionButton;
    // End of variables declaration                   
}

