/*
 * Copyright 2015 Laszlo Balazs-Csiki
 *
 * This file is part of IDCRTT. IDCRTT is free software: you
 * can redistribute it and/or modify it under the terms of the GNU
 * General Public License, version 3 as published by the Free
 * Software Foundation.
 *
 * IDCRTT is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with IDCRTT. If not, see <http://www.gnu.org/licenses/>.
 */

package pixelitor;
 
 /** The main class
 */

import java.util.logging.Logger;
import java.util.*;
import java.io.*;
import javax.swing.*;
import javax.swing.event.*;

import Pixelitor.*;
import java.awt.EventQueue;
import java.awt.GraphicsEnvironment;
import net.jafama.FastMath;
import pixelitor.io.OpenSaveManager;
import pixelitor.tools.FgBgColorSelector;
import pixelitor.utils.AppPreferences;
import pixelitor.utils.Dialogs;
import pixelitor.utils.Utils;
/*
import ClipArtIdeas.ClipArtIdeas1;
import Credits.Credits;
import Instruction.Instruction;
import dictionary.categoriesMain;
import templates.templatesMain;
*/
public class IDCRTT extends javax.swing.JFrame{
    /**
     * Utility class with static methods
     */
    /**
     * Creates new form NumberAddition
     */
    public IDCRTT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ButtonIntruction = new javax.swing.JButton();
        ButtonDictionary = new javax.swing.JButton();
        ButtonCreate = new javax.swing.JButton();
        ButtonTemplate = new javax.swing.JButton();
        ButtonClip = new javax.swing.JButton();
        ButtonExit = new javax.swing.JButton();
        ButtonCredits = new javax.swing.JButton();
        ButtonVideo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(null);

        ButtonIntruction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/b_instructions.png"))); // NOI18N
        ButtonIntruction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonIntructionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonIntructionMouseExited(evt);
            }
        });
        ButtonIntruction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
//////                ButtonIntructionActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonIntruction);
        ButtonIntruction.setBounds(590, 410, 200, 80);

        ButtonDictionary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/b_dictionary.png"))); // NOI18N
        ButtonDictionary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonDictionaryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonDictionaryMouseExited(evt);
            }
        });
        ButtonDictionary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDictionaryActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonDictionary);
        ButtonDictionary.setBounds(590, 40, 200, 80);

        ButtonCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/b_create.png"))); // NOI18N
        ButtonCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonCreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonCreateMouseExited(evt);
            }
        });
        ButtonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCreateActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonCreate);
        ButtonCreate.setBounds(590, 130, 200, 80);

        ButtonTemplate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/b_templates.png"))); // NOI18N
        ButtonTemplate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonTemplateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonTemplateMouseExited(evt);
            }
        });
        ButtonTemplate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
/////                ButtonTemplateActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonTemplate);
        ButtonTemplate.setBounds(590, 220, 200, 80);

        ButtonClip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/b_clipartideas.png"))); // NOI18N
        ButtonClip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonClipMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonClipMouseExited(evt);
            }
        });
        ButtonClip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
/////                ButtonClipActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonClip);
        ButtonClip.setBounds(590, 320, 200, 80);

        ButtonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/b_exit.png"))); // NOI18N
        ButtonExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonExitMouseExited(evt);
            }
        });
        ButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonExitActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonExit);
        ButtonExit.setBounds(720, 540, 70, 50);

        ButtonCredits.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/b_credits.png"))); // NOI18N
        ButtonCredits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonCreditsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonCreditsMouseExited(evt);
            }
        });
        ButtonCredits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
/////                ButtonCreditsActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonCredits);
        ButtonCredits.setBounds(600, 540, 110, 50);

        ButtonVideo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/b_video.png"))); // NOI18N
        ButtonVideo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonVideoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonVideoMouseExited(evt);
            }
        });
        ButtonVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
//////                ButtonVideoActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonVideo);
        ButtonVideo.setBounds(10, 540, 70, 50);

        /*jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        
        //ImageIcon icon = createImageIcon("/images/buttons/mainMenu.png","a pretty but meaningless splat");
        //label1 = new JLabel("Image and Text", icon, JLabel.CENTER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("mainMenu.png"))); // NOI18N 
        //ImageIcon ii = new ImageIcon(getClass().getResource("/images/buttons/mainMenu.png"));
        //jLabel1.setIcon(ii));
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        */
        
        
        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        //jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainMenu.png"))); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IDCRTT/mainMenu.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 804, 604);
        
        
        
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>                        
    private static final Logger LOG = Logger.getLogger(IDCRTT.class.getName());

    private void ButtonExitActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // Exit button
         System.exit(0);
    }
/*
    private void ButtonTemplateActionPerformed(java.awt.event.ActionEvent evt) {                                               
        templatesMain tMain = new templatesMain();
        tMain.setSize(820,660); //pack();
        tMain.setVisible(true);
        tMain.setLocationRelativeTo(null);
        this.setVisible(false); //radi
    }                                              

    private void ButtonVideoActionPerformed(java.awt.event.ActionEvent evt) {                                            
        IntroVideo IntroVideo = new IntroVideo();
        IntroVideo.setSize(820,660); //pack();
        IntroVideo.setVisible(true);
        IntroVideo.setLocationRelativeTo(null);
        this.setVisible(false); //radi
    }                                           

    private void ButtonClipActionPerformed(java.awt.event.ActionEvent evt) {                                           
        ClipArtIdeas1 tMain = new ClipArtIdeas1();
        tMain.setSize(820,660); //pack();
        tMain.setVisible(true);
        tMain.setLocationRelativeTo(null);
        this.setVisible(false); //radi
    }                                          
*/
    private void ButtonCreateActionPerformed(java.awt.event.ActionEvent evt) {                                             
        /* this.setVisible(false); //radi
        categoriesMain tMain = new categoriesMain();
        tMain.setSize(820,660); //pack();
        tMain.setVisible(true);
        tMain.setLocationRelativeTo(null);*/
        
        
        // allows to put the app into development mode by
        // adding -Dpixelitor.development=true to the command line
        if ("true".equals(System.getProperty("pixelitor.development"))) {
            Utils.checkThatAssertionsAreEnabled();
            Build.CURRENT = Build.DEVELOPMENT;
        }

        setupForMacintosh();

        ExceptionHandler.INSTANCE.register();
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    String[] args = new String[0];
                    createAndShowGUI(args);
                    
                    // this will run on a different thread, but call it
                    // here because it is IO-intensive and it should not
                    // slow down the loading of the GUI
                    preloadFontNames();
                } catch (Exception e) {
                    Dialogs.showExceptionDialog(e);
                }
            }
        });

        // Force the initialization of FastMath look-up tables now
        // so that later no unexpected delays happen.
        // This is OK because static initializers are thread safe.
        FastMath.cos(0.1);
//        Pixelitor Pix = new Pixelitor();
//        Pix.createAndShowGUI();
//        this.setVisible(false);
    }                                            
    private static void preloadFontNames() {
        // The initial loading of font names can take some noticeable time.
        // Preload them to speed up the first start of the text creation dialog
        Runnable loadFontsTask = () -> {
            GraphicsEnvironment localGE = GraphicsEnvironment.getLocalGraphicsEnvironment();
            // the results are cached, no need to cached them here
            localGE.getAvailableFontFamilyNames();
        };
        new Thread(loadFontsTask).start();
    }

    private static void setupForMacintosh() {
        // this works
        System.setProperty("com.apple.mrj.application.apple.menu.about.name", "Pixelitor");

        // this is respected only by the native Aqua look-and-feel
        System.setProperty("apple.laf.useScreenMenuBar", "true");
    }

    private static void createAndShowGUI(String[] args) {
        assert SwingUtilities.isEventDispatchThread();

        setLookAndFeel();

        PixelitorWindow pw = PixelitorWindow.getInstance();
        Dialogs.setMainWindowInitialized(true);

        if (args.length > 0) {
            openFilesGivenAsProgramArguments(args);
        } else {
            // ensure that the focus is not grabbed by a textfield
            // so that the keyboard shortcuts work properly
            FgBgColorSelector.INSTANCE.requestFocus();
        }

        TipsOfTheDay.showTips(pw, false);

        afterStartTestActions(pw);
    }

    private static void setLookAndFeel() {
        try {
            UIManager.setLookAndFeel(AppPreferences.getLookAndFeelClass());
        } catch (Exception e) {
            Dialogs.showExceptionDialog(e);
        }
    }

    private static void openFilesGivenAsProgramArguments(String[] args) {
        for (String fileName : args) {
            File f = new File(fileName);
            if (f.exists()) {
                OpenSaveManager.openFile(f);
            } else {
                Dialogs.showErrorDialog("File not found", "The file \"" + f.getAbsolutePath() + "\" does not exist");
            }
        }
    }

    /**
     * A possibility for automatic debugging or testing
     */
    private static void afterStartTestActions(PixelitorWindow pw) {
        if (Build.CURRENT == Build.FINAL) {
            // in the final builds nothing should run
            return;
        }
    }
    
    private void ButtonDictionaryActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        categoriesMain tMain = new categoriesMain();
        tMain.setSize(820,660); //pack();
        tMain.setVisible(true);
        tMain.setLocationRelativeTo(null);
        this.setVisible(false); //radi        
    }                                                

    private void ButtonCreateMouseEntered(java.awt.event.MouseEvent evt) {                                          
        ButtonCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/b_create-hover.png")));
    }                                         

    private void ButtonCreateMouseExited(java.awt.event.MouseEvent evt) {                                         
         ButtonCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/b_create.png")));
    }                                        

    private void ButtonDictionaryMouseEntered(java.awt.event.MouseEvent evt) {                                              
         ButtonDictionary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/b_dictionary-hover.png")));
    }                                             

    private void ButtonDictionaryMouseExited(java.awt.event.MouseEvent evt) {                                             
        ButtonDictionary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/b_dictionary.png")));
    }                                            

    private void ButtonTemplateMouseEntered(java.awt.event.MouseEvent evt) {                                            
         ButtonTemplate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/b_templates-hover.png")));
    }                                           

    private void ButtonTemplateMouseExited(java.awt.event.MouseEvent evt) {                                           
       ButtonTemplate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/b_templates.png")));
    }                                          

    private void ButtonClipMouseEntered(java.awt.event.MouseEvent evt) {                                        
       ButtonClip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/b_clipartideas-hover.png")));
    }                                       

    private void ButtonClipMouseExited(java.awt.event.MouseEvent evt) {                                       
        ButtonClip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/b_clipartideas.png")));
    }                                      

    private void ButtonIntructionMouseEntered(java.awt.event.MouseEvent evt) {                                              
       ButtonIntruction.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/buttons/b_instructions-hover.png")));
    }                                             

    private void ButtonIntructionMouseExited(java.awt.event.MouseEvent evt) {                                             
        ButtonIntruction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/b_instructions.png")));
    }                                            

    private void ButtonExitMouseEntered(java.awt.event.MouseEvent evt) {                                        
         ButtonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/b_exit-hover.png")));
    }                                       

    private void ButtonExitMouseExited(java.awt.event.MouseEvent evt) {                                       
        ButtonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/b_exit.png")));
    }                                      

    private void ButtonCreditsMouseEntered(java.awt.event.MouseEvent evt) {                                           
        ButtonCredits.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/b_credits-hover.png")));
    }                                          

    private void ButtonCreditsMouseExited(java.awt.event.MouseEvent evt) {                                          
        ButtonCredits.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/b_credits.png")));
    }                                         

    private void ButtonVideoMouseEntered(java.awt.event.MouseEvent evt) {                                         
        ButtonVideo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/b_video-hover.png")));
    }                                        

    private void ButtonVideoMouseExited(java.awt.event.MouseEvent evt) {                                        
       ButtonVideo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/b_video.png")));
    }                                       
/*
    private void ButtonCreditsActionPerformed(java.awt.event.ActionEvent evt) {                                              
        Credits tMain = new Credits();
        tMain.setSize(820,660); //pack();
        tMain.setVisible(true);
        tMain.setLocationRelativeTo(null);
        this.setVisible(false); //radi
    }                                             

    private void ButtonIntructionActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        Instruction tMain = new Instruction();
        tMain.setSize(820,660); //pack();
        tMain.setVisible(true);
        tMain.setLocationRelativeTo(null);
        this.setVisible(false); //radi
    } 
 */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IDCRTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IDCRTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IDCRTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IDCRTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IDCRTT tMain = new IDCRTT();
                tMain.setSize(820,660); //pack();
                tMain.setVisible(true);
                tMain.setLocationRelativeTo(null);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton ButtonClip;
    private javax.swing.JButton ButtonCreate;
    private javax.swing.JButton ButtonCredits;
    private javax.swing.JButton ButtonDictionary;
    private javax.swing.JButton ButtonExit;
    private javax.swing.JButton ButtonIntruction;
    private javax.swing.JButton ButtonTemplate;
    private javax.swing.JButton ButtonVideo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration
    

}
